language: java
branches:
  only:
    - "master"
script: mvn javadoc:javadoc && mvn package
deploy:
  - provider: pages
    github-token: $GITHUB_TOKEN
    local-dir: "target/site/apidocs/"
    skip-cleanup: true
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: "target/usf.jar"
    skip_cleanup: true
    on:
      tags: true
      repo: kimbtech/USF
after_success: mvn jacoco:report coveralls:report
